---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nearandnin/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp dist/.htaccess $DEPLOYPATH 2>/dev/null || true

