import { useState } from 'react';
import { HelpCircle, Book, MessageCircle, FileText, Video, Mail, ChevronDown, Search, Zap, ArrowRight } from 'lucide-react';
import AdminLayout from '../../components/admin/layout/AdminLayout';

const faqs = [
  {
    q: 'How do I add a new product?',
    a: 'Go to Products → Add Product. Fill in the product details (name, price, category, images), set stock status, and save. You can also use Quick Add from the product list.',
  },
  {
    q: 'How do I update order status?',
    a: 'Open Orders, click on an order to view details, then use the status dropdown to change it (e.g. pending → store_accepted → preparing → ready_for_pickup → in_transit → delivered).',
  },
  {
    q: 'How do I manage categories?',
    a: 'Go to Categories to add, edit, or delete categories. Categories control how products are grouped. Only categories with products are shown to customers.',
  },
  {
    q: 'How do I export reports?',
    a: 'In Reports, select the time period (7/30/90/365 days), then click Export to download the report as JSON with revenue, orders, and product data.',
  },
  {
    q: 'How do I create admin accounts?',
    a: 'Super admins can go to Admin Management → Create Admin. Set email, password, role (super_admin or admin), and permissions. Admins can have granular permissions like products:read, orders:update, etc.',
  },
  {
    q: 'How do I assign a delivery partner?',
    a: 'Delivery assignment is managed from the Delivery page. Delivery partners can be configured in the database and linked to store orders via the delivery management interface.',
  },
  {
    q: 'How does the notification system work?',
    a: 'Admin notifications are auto-generated by database triggers. New orders and new customer registrations instantly appear in the Notifications page. Push notifications can be sent to delivery drivers from the same page.',
  },
  {
    q: 'How do I send push notifications to drivers?',
    a: 'Go to Notifications → Send Push Notification. Select "Delivery Drivers" as the target audience, write your message, and hit Send. This uses the Expo push token stored for each driver.',
  },
];

const helpSections = [
  {
    icon: Book,
    title: 'Documentation',
    description: 'Comprehensive guides for every feature',
    color: 'from-blue-500 to-indigo-500',
    bg: 'bg-blue-50',
    iconColor: 'text-blue-600',
    items: ['Getting Started Guide', 'Product Management', 'Order Processing', 'Customer Management', 'Reports & Analytics'],
  },
  {
    icon: Video,
    title: 'Video Tutorials',
    description: 'Step-by-step video walkthroughs',
    color: 'from-violet-500 to-purple-500',
    bg: 'bg-violet-50',
    iconColor: 'text-violet-600',
    items: ['Dashboard Overview', 'Adding Products', 'Managing Orders', 'Using Reports', 'Admin Management'],
  },
  {
    icon: Zap,
    title: 'Quick Actions',
    description: 'Common tasks done in seconds',
    color: 'from-amber-500 to-orange-500',
    bg: 'bg-amber-50',
    iconColor: 'text-amber-600',
    items: ['Add a product', 'Update order status', 'View today\'s revenue', 'Send push notification', 'Export report'],
  },
  {
    icon: MessageCircle,
    title: 'Support',
    description: 'Get help from our team',
    color: 'from-emerald-500 to-teal-500',
    bg: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
    items: ['Live Chat Support', 'Email Support', 'Ticket System', 'Community Forum', 'Contact Information'],
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className={`border rounded-xl transition-all duration-200 overflow-hidden cursor-pointer ${open ? 'border-emerald-200 bg-emerald-50/40' : 'border-gray-200 bg-white hover:border-gray-300'}`}
      onClick={() => setOpen(!open)}
    >
      <div className="flex items-center justify-between px-5 py-4">
        <p className={`text-sm font-semibold pr-4 ${open ? 'text-emerald-700' : 'text-gray-800'}`}>{q}</p>
        <ChevronDown
          size={16}
          className={`flex-shrink-0 transition-transform duration-200 ${open ? 'rotate-180 text-emerald-500' : 'text-gray-400'}`}
        />
      </div>
      {open && (
        <div className="px-5 pb-4">
          <div className="w-full h-px bg-emerald-200 mb-3" />
          <p className="text-sm text-gray-600 leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  );
}

const HelpPage = () => {
  const [search, setSearch] = useState('');

  const filteredFaqs = faqs.filter(
    f => f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <AdminLayout>
      <div className="space-y-8 max-w-5xl">
        {/* Hero */}
        <div className="relative rounded-2xl overflow-hidden bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 p-8 text-white shadow-lg">
          <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 70% 50%, white 0%, transparent 60%)' }} />
          <div className="relative">
            <div className="flex items-center gap-2 mb-3">
              <HelpCircle size={20} className="text-emerald-100" />
              <span className="text-sm font-semibold text-emerald-100 uppercase tracking-wider">Help Center</span>
            </div>
            <h1 className="text-3xl font-bold mb-2">How can we help?</h1>
            <p className="text-emerald-100 text-sm mb-6">Find answers, guides, and support for the Near & Now admin panel</p>
            <div className="relative max-w-md">
              <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" />
              <input
                type="text"
                placeholder="Search help topics..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full pl-10 pr-4 py-3 rounded-xl bg-white text-gray-800 text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-white/50 shadow-sm"
              />
            </div>
          </div>
        </div>

        {/* Help Sections */}
        <div>
          <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Resources</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {helpSections.map((section) => {
              const Icon = section.icon;
              return (
                <div key={section.title} className="group rounded-2xl bg-white border border-gray-100 shadow-sm p-5 hover:shadow-md hover:-translate-y-0.5 transition-all duration-200 cursor-pointer">
                  <div className={`w-12 h-12 rounded-xl ${section.bg} flex items-center justify-center mb-4`}>
                    <Icon size={22} className={section.iconColor} />
                  </div>
                  <h3 className="text-sm font-bold text-gray-900 mb-1">{section.title}</h3>
                  <p className="text-xs text-gray-500 mb-4">{section.description}</p>
                  <ul className="space-y-1.5">
                    {section.items.map(item => (
                      <li key={item} className="flex items-center gap-2 text-xs text-gray-600 hover:text-emerald-600 transition-colors">
                        <ArrowRight size={10} className="text-gray-300 flex-shrink-0" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              );
            })}
          </div>
        </div>

        {/* FAQ */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider">
              Frequently Asked Questions
            </h2>
            <span className="text-xs text-gray-400">{filteredFaqs.length} topics</span>
          </div>

          {filteredFaqs.length === 0 ? (
            <div className="text-center py-12 rounded-2xl bg-gray-50 border border-gray-100">
              <FileText size={32} className="text-gray-300 mx-auto mb-3" />
              <p className="text-sm font-medium text-gray-500">No results for &quot;{search}&quot;</p>
              <p className="text-xs text-gray-400 mt-1">Try a different search term</p>
            </div>
          ) : (
            <div className="space-y-2">
              {filteredFaqs.map((faq, i) => (
                <FAQItem key={i} q={faq.q} a={faq.a} />
              ))}
            </div>
          )}
        </div>

        {/* Contact Support */}
        <div className="rounded-2xl bg-gradient-to-r from-slate-800 to-slate-900 p-6 flex items-center justify-between gap-6 shadow-sm">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-xl bg-white/10 flex items-center justify-center flex-shrink-0">
              <Mail size={22} className="text-white" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white mb-1">Still need help?</h3>
              <p className="text-sm text-slate-400">Our support team is ready to assist you with any questions</p>
            </div>
          </div>
          <a
            href="mailto:support@nearandnow.com"
            className="flex-shrink-0 flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-500 text-white text-sm font-semibold hover:bg-emerald-400 transition-colors shadow-sm"
          >
            <Mail size={15} />
            Contact Support
          </a>
        </div>
      </div>
    </AdminLayout>
  );
};

export default HelpPage;
